export const LIST_APPLICATIONS = 'LIST_APPLICATIONS';
export const LIST_APPLICATION_INSTANCES = 'LIST_APPLICATION_INSTANCES';
export const LIST_LIFECYCLES = 'LIST_LIFECYCLES';
export const LIST_ENVIRONMENTS = 'LIST_ENVIRONMENTS';
export const SELECT_ENVIRONMENT = 'SELECT_ENVIRONMENT';
