{{- $fullName := include "cmdb.fullname" . -}}
{{- $appName := include "cmdb.name" . -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ $fullName }}-migrate
{{- if .Values.cmdb }}
  namespace: {{ .Values.nameSpace }}
{{- end }}
  labels:
    app: {{ $appName }}
    chart: {{ template "cmdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  restartPolicy: Never
  initContainers:
    - name: init-container1
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumeMounts:
        - mountPath: "/cmdb-migrations"
          name: migrations
      command:
        - "cp"
        - "-r"
        - "/db/migrations"
        - "/cmdb-migrations"
{{- if .Values.postgresql.enabled }}
    - name: init-database
      image: busybox
      command: ['sh', '-c', 'until nslookup {{ template "postgresql.primary.fullname" . }}; do echo waiting for cmdb database; sleep 10; done;']
{{- end }}
  containers:
  - name: {{ .Values.migration.name }}
    env:
    - name: DATABASE_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: {{ template "postgresql.primary.fullname" . }}
          key: CMDB_DATABASE_HOST
    - name: DATABASE_NAME
      valueFrom:
        configMapKeyRef:
          name: {{ template "postgresql.primary.fullname" . }}
          key: CMDB_DATABASE_NAME
    - name: DATABASE_USER
      valueFrom:
        configMapKeyRef:
          name: {{ template "postgresql.primary.fullname" . }}
          key: CMDB_DATABASE_USER
  {{- if .Values.postgresql.enabled }}
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ template "postgresql.primary.fullname" . }}
          key: postgresql-password
{{- end }}
    - name: CONFIG_FILE
      value: defaults
    image: {{ .Values.migration.image }}:{{ .Values.migration.version }}
    imagePullPolicy: {{ .Values.migration.imagePullPolicy }}
    volumeMounts:
      - mountPath: /cmdb-migrations
        name: migrations
    command:
      - /migrate
    args:
      - "--verbose"
      - "--source"
      - "file:///cmdb-migrations/migrations"
      - up
      # to get to a particular level append following
      #- "2"
  volumes:
    - name: migrations
      emptyDir: {}
