{{- $fullName := include "cmdb.fullname" . -}}
apiVersion: v1
kind: Pod
metadata:
    namespace: {{ .Release.Namespace }}
    name: {{ $fullName }}-migration
spec:
  restartPolicy: OnFailure
  initContainers:
  - name: migration-source
    image: "{{ .Values.cmdb.image.repository }}:{{ .Values.cmdb.image.tag | default .Chart.AppVersion }}"
    imagePullPolicy: {{ .Values.cmdb.image.pullPolicy }}
    volumeMounts:
    - mountPath: "/service-migrations"
      name: migrations
    command:
    - "cp"
    - "-r"
    - "/db/migrations"
    - "/service-migrations"
  containers:
    - name: migration
      image: {{ .Values.cmdb.migration.image }}:{{ .Values.cmdb.migration.version }}
      imagePullPolicy: {{ .Values.cmdb.migration.imagePullPolicy }}
      volumeMounts:
      - mountPath: "/service-migrations"
        name: migrations
      env:
      - name: POSTGRES_USER
        valueFrom:
          configMapKeyRef:
            name: {{ $fullName }}
            key: CMDB_DATABASE_USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: {{ .Release.Name }}-postgresql
            key: postgresql-password
      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: {{ $fullName }}
            key: CMDB_DATABASE_NAME
      - name: POSTGRES_HOST
        valueFrom:
          configMapKeyRef:
            name: {{ $fullName }}
            key: CMDB_DATABASE_HOST
      - name: POSTGRES_PORT
        value: {{ .Values.postgresql.service.port | quote }}
      - name: POSTGRES_SSLMODE
        value: {{ template "sslmode" . }}

      - name: LOGGING_LEVEL
        value: {{ .Values.cmdb.logLevel }}
      - name: dsn
        value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=$(POSTGRES_SSLMODE)
      command:
      - /migrate
      args:
      - "--source"
      - "file://service-migrations/migrations"
      - "--database.dsn"
      - "$(dsn)"
      - "up"
  volumes:
  - name: migrations
    emptyDir: {}
