apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmdb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cmdb.service.type }}
  ports:
    {{- range .Values.cmdb.service.ports }}
    - port: {{ .port }}
      protocol: {{ .protocol }}
      name: {{ .name }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- end }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "cmdb.selectorLabels" . | nindent 4 }}
