// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/seizadi/cmdb/pkg/pb/cmdb.proto

package pb // import "github.com/seizadi/cmdb/pkg/pb"

import options "github.com/infobloxopen/protoc-gen-atlas-query-validate/options"
import query "github.com/infobloxopen/atlas-app-toolkit/query"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.

var CmdbMethodsRequireFilteringValidation = map[string]map[string]options.FilteringOption{}
var CmdbMethodsRequireSortingValidation = map[string][]string{}
var CmdbMethodsRequireFieldSelectionValidation = map[string][]string{}

func CmdbValidateFiltering(methodName string, f *query.Filtering) error {
	info, ok := CmdbMethodsRequireFilteringValidation[methodName]
	if !ok {
		return nil
	}
	return options.ValidateFiltering(f, info)
}
func CmdbValidateSorting(methodName string, s *query.Sorting) error {
	info, ok := CmdbMethodsRequireSortingValidation[methodName]
	if !ok {
		return nil
	}
	return options.ValidateSorting(s, info)
}
func CmdbValidateFieldSelection(methodName string, s *query.FieldSelection) error {
	info, ok := CmdbMethodsRequireFieldSelectionValidation[methodName]
	if !ok {
		return nil
	}
	return options.ValidateFieldSelection(s, info)
}
