// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/seizadi/cmdb/pkg/pb/cmdb.proto

package pb // import "github.com/seizadi/cmdb/pkg/pb"

import options "github.com/infobloxopen/protoc-gen-atlas-query-validate/options"
import query "github.com/infobloxopen/atlas-app-toolkit/query"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/infobloxopen/protoc-gen-atlas-validate/options"
import _ "google.golang.org/genproto/protobuf/field_mask"

// Reference imports to suppress errors if they are not otherwise used.

var CmdbMethodsRequireFilteringValidation = map[string]map[string]options.FilteringOption{
	"/api.cmdb.Regions/List": map[string]options.FilteringOption{
		"id":          options.FilteringOption{ValueType: options.QueryValidate_STRING},
		"name":        options.FilteringOption{ValueType: options.QueryValidate_STRING},
		"description": options.FilteringOption{ValueType: options.QueryValidate_STRING},
	},
}
var CmdbMethodsRequireSortingValidation = map[string][]string{
	"/api.cmdb.Regions/List": []string{
		"id",
		"name",
		"description",
	},
}
var CmdbMethodsRequireFieldSelectionValidation = map[string][]string{
	"/api.cmdb.Regions/Read": {
		"id",
		"name",
		"description",
	},
	"/api.cmdb.Regions/List": {
		"id",
		"name",
		"description",
	},
}

func CmdbValidateFiltering(methodName string, f *query.Filtering) error {
	info, ok := CmdbMethodsRequireFilteringValidation[methodName]
	if !ok {
		return nil
	}
	return options.ValidateFiltering(f, info)
}
func CmdbValidateSorting(methodName string, s *query.Sorting) error {
	info, ok := CmdbMethodsRequireSortingValidation[methodName]
	if !ok {
		return nil
	}
	return options.ValidateSorting(s, info)
}
func CmdbValidateFieldSelection(methodName string, s *query.FieldSelection) error {
	info, ok := CmdbMethodsRequireFieldSelectionValidation[methodName]
	if !ok {
		return nil
	}
	return options.ValidateFieldSelection(s, info)
}
