// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/seizadi/cmdb/pkg/pb/service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/seizadi/cmdb/pkg/pb/service.proto

It has these top-level messages:
	VersionResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cmdb service

type CmdbClient interface {
	GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type cmdbClient struct {
	cc *grpc.ClientConn
}

func NewCmdbClient(cc *grpc.ClientConn) CmdbClient {
	return &cmdbClient{cc}
}

func (c *cmdbClient) GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/service.Cmdb/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cmdb service

type CmdbServer interface {
	GetVersion(context.Context, *google_protobuf.Empty) (*VersionResponse, error)
}

func RegisterCmdbServer(s *grpc.Server, srv CmdbServer) {
	s.RegisterService(&_Cmdb_serviceDesc, srv)
}

func _Cmdb_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdbServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Cmdb/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdbServer).GetVersion(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cmdb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Cmdb",
	HandlerType: (*CmdbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _Cmdb_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/seizadi/cmdb/pkg/pb/service.proto",
}

func init() { proto.RegisterFile("github.com/seizadi/cmdb/pkg/pb/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4a, 0xf4, 0x30,
	0x14, 0x85, 0x99, 0x9f, 0x1f, 0x47, 0xb3, 0x51, 0xba, 0x90, 0x52, 0x5d, 0xe8, 0xb8, 0x11, 0x9c,
	0xc9, 0x05, 0xdd, 0x39, 0x3b, 0x45, 0xdc, 0xca, 0x2c, 0x44, 0xdc, 0x25, 0xed, 0x6d, 0x0c, 0xb6,
	0xb9, 0xa1, 0xc9, 0x54, 0xc7, 0xa5, 0xaf, 0xe0, 0xa3, 0xf9, 0x0a, 0x3e, 0x88, 0x4c, 0x93, 0x4a,
	0x51, 0x71, 0x97, 0x73, 0xef, 0x3d, 0xe7, 0x83, 0x13, 0x36, 0x55, 0xda, 0x3f, 0x2c, 0x25, 0xcf,
	0xa9, 0x06, 0x87, 0xfa, 0x45, 0x14, 0x1a, 0xf2, 0xba, 0x90, 0x60, 0x1f, 0x15, 0x58, 0x09, 0x0e,
	0x9b, 0x56, 0xe7, 0xc8, 0x6d, 0x43, 0x9e, 0x92, 0x71, 0x94, 0xd9, 0x9e, 0x22, 0x52, 0x15, 0x42,
	0x37, 0x96, 0xcb, 0x12, 0xb0, 0xb6, 0x7e, 0x15, 0xae, 0xb2, 0xfd, 0xb8, 0x14, 0x56, 0x83, 0x30,
	0x86, 0xbc, 0xf0, 0x9a, 0x8c, 0x8b, 0xdb, 0xf9, 0x80, 0x58, 0xad, 0x4a, 0x1f, 0x32, 0xf2, 0x99,
	0x42, 0x33, 0x6b, 0x45, 0xa5, 0x0b, 0xe1, 0x11, 0x7e, 0x3c, 0xa2, 0x79, 0x3a, 0x38, 0x76, 0x4f,
	0x42, 0x29, 0x6c, 0x80, 0x6c, 0x17, 0xff, 0x0b, 0xea, 0x7c, 0x80, 0xd2, 0xa6, 0x24, 0x59, 0xd1,
	0x33, 0x59, 0x34, 0x43, 0xa4, 0xa2, 0xa6, 0xfe, 0x8a, 0x58, 0x8b, 0xe0, 0x9d, 0x9c, 0xb0, 0xed,
	0x5b, 0x6c, 0x9c, 0x26, 0xb3, 0x40, 0x67, 0xc9, 0x38, 0x4c, 0x52, 0x36, 0x6e, 0xc3, 0x28, 0x1d,
	0x1d, 0x8c, 0x8e, 0xb7, 0x16, 0xbd, 0x3c, 0xbd, 0x63, 0xff, 0x2f, 0xeb, 0x42, 0x26, 0x37, 0x8c,
	0x5d, 0xa3, 0x8f, 0xbe, 0x64, 0x97, 0x87, 0x22, 0x78, 0xdf, 0x12, 0xbf, 0x5a, 0xb7, 0x94, 0xa5,
	0xbc, 0x6f, 0xf5, 0x1b, 0x61, 0xb2, 0xf3, 0xfa, 0xfe, 0xf1, 0xf6, 0x8f, 0x25, 0x9b, 0x10, 0x93,
	0x2f, 0x8e, 0xee, 0x0f, 0xff, 0xfe, 0xa1, 0xb9, 0x95, 0x72, 0xa3, 0x03, 0x9c, 0x7d, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x8b, 0xd0, 0xfe, 0xa7, 0xcd, 0x01, 0x00, 0x00,
}
